version: 2
jobs:
  TestOne:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hi one"
  TestTwo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hi two"
workflows:
  version: 2
  TestOne_and_TestTwo:
    jobs:
      - TestOne
      - TestTwo
